#!/usr/bin/env python3
"""
Database backup script using psycopg2
This script connects to the Neon database and creates a SQL dump
"""

import psycopg2
import sys
from urllib.parse import urlparse, parse_qs

# Connection string
conn_string = "postgresql://neondb_owner:YOUR_PASSWORD@ep-purple-union-ab9djram-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

print("🔗 Connecting to Neon database...")

try:
    # Connect to database
    conn = psycopg2.connect(conn_string)
    conn.set_session(autocommit=True)
    cur = conn.cursor()
    
    print("✅ Connected successfully!")
    print("📦 Creating database backup...")
    
    # Get database name
    cur.execute("SELECT current_database();")
    db_name = cur.fetchone()[0]
    
    # Open output file
    output_file = "database_backup.sql"
    
    with open(output_file, 'w', encoding='utf-8') as f:
        # Write header
        f.write(f"-- Database Backup\n")
        f.write(f"-- Database: {db_name}\n")
        f.write(f"-- Generated by pg_dump equivalent script\n")
        f.write(f"\n")
        
        # Get all tables
        cur.execute("""
            SELECT table_name 
            FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_type = 'BASE TABLE'
            ORDER BY table_name;
        """)
        
        tables = cur.fetchall()
        
        if not tables:
            print("⚠️  No tables found in database")
            f.write("-- No tables found\n")
        else:
            print(f"📋 Found {len(tables)} tables")
            
            # For each table, get structure and data
            for (table_name,) in tables:
                print(f"   Dumping table: {table_name}")
                
                # Get table structure
                cur.execute(f"""
                    SELECT column_name, data_type, character_maximum_length, 
                           is_nullable, column_default
                    FROM information_schema.columns
                    WHERE table_schema = 'public' 
                    AND table_name = '{table_name}'
                    ORDER BY ordinal_position;
                """)
                
                columns = cur.fetchall()
                
                # Write CREATE TABLE statement
                f.write(f"\n-- Table: {table_name}\n")
                f.write(f"DROP TABLE IF EXISTS {table_name} CASCADE;\n")
                f.write(f"CREATE TABLE {table_name} (\n")
                
                col_defs = []
                for col in columns:
                    col_name, data_type, max_length, is_nullable, default = col
                    col_def = f"    {col_name} {data_type}"
                    if max_length:
                        col_def += f"({max_length})"
                    if is_nullable == 'NO':
                        col_def += " NOT NULL"
                    if default:
                        col_def += f" DEFAULT {default}"
                    col_defs.append(col_def)
                
                f.write(",\n".join(col_defs))
                f.write("\n);\n\n")
                
                # Get table data
                cur.execute(f'SELECT * FROM "{table_name}";')
                rows = cur.fetchall()
                
                if rows:
                    # Get column names
                    col_names = [desc[0] for desc in cur.description]
                    f.write(f"-- Data for table: {table_name}\n")
                    
                    for row in rows:
                        values = []
                        for val in row:
                            if val is None:
                                values.append("NULL")
                            elif isinstance(val, str):
                                # Escape single quotes
                                val_escaped = val.replace("'", "''")
                                values.append(f"'{val_escaped}'")
                            else:
                                values.append(str(val))
                        
                        f.write(f"INSERT INTO {table_name} ({', '.join(col_names)}) VALUES ({', '.join(values)});\n")
                    f.write("\n")
    
    print(f"✅ Backup created successfully: {output_file}")
    
    cur.close()
    conn.close()
    
except psycopg2.Error as e:
    print(f"❌ Database error: {e}")
    sys.exit(1)
except Exception as e:
    print(f"❌ Error: {e}")
    sys.exit(1)

